repos:
-   repo: local
    hooks:
    -   id: cargo-fmt
        name: cargo fmt (format)
        entry: cargo fmt
        language: system
        files: '\.rs$'
        pass_filenames: false
    -   id: cargo-clippy
        name: cargo clippy (deny warnings)
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        files: '\.rs$'
        pass_filenames: false
